### ISSUE TITLE
issue: race-condition for initializing stores when using URL params

### ISSUE THREAD

**Issue by mr-zwets** [cashonize/cashonize-wallet#24]
Currently there can be a race condition where Cashonize hasn't initialized yet, see:
https://github.com/cashonize/cashonize-wallet/blob/main/src/pages/WalletPage.vue#L43

@jimtendo suggested 3 possible fixes

1. to use a boot file to initialize the store, `/boot/...` files run before any components/pages are mounted

2. might be able to replace the code above with something in the stores/store.ts that just uses JS (or Vue router) to read the URL *after* WC and CC are initialized.

3. as a hotfix, could increase the timeout

I haven't run into the race-condition while testing

**Comment by jimtendo** [comment]
I'm in Australia, so probably a few more network hops away from most services relative to Europe.

Occasionally, I do slip under the 500ms, but generally it's a miss from where I'm located.

A few timings measured below (most seem to hover between 1000ms-1500ms from here... 2000ms+ appears infrequent):

![image](https://github.com/user-attachments/assets/0bafbf5e-55a2-4242-8c0f-9027f7877b49)

![image](https://github.com/user-attachments/assets/2d7b42ca-1750-495d-b5c9-258bd6419bf5)

![image](https://github.com/user-attachments/assets/60e7e836-7a96-4858-82e3-cbded6ae4fed)

**Comment by mr-zwets** [comment]
this issue should now be resolved (as of v0.2.3) with method 2. so without the need for a boot-file.

Thanks @jimtendo for helping with the fix!
